version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jn316rom623
      MYSQL_DATABASE: academy
      MYSQL_USER: academy
      MYSQL_PASSWORD: jn316rom623
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: